### ISSUE TITLE
problem with --perms in sftp

### ISSUE THREAD

**Issue by daybug** [juicedata/juicesync#110]
debug logs as follow:

2021/03/23 15:17:30.195700 juicefs[86870] <DEBUG>: Iterating objects from root@xx.xx.xx.xx:/opt/data/ start ""
**panic: interface conversion: *object.sftpStore is not object.FileSystem: missing method Chmod**

goroutine 53 [running]:
github.com/juicedata/juicefs/pkg/sync.worker(0xc000498120, 0x26fa460, 0xc0000a9480, 0x26fade0, 0xc000092300, 0xc000309ea0)
	/home/runner/go/pkg/mod/github.com/juicedata/juicefs@v0.11.1-0.20210317124003-5f38427ccdb9/pkg/sync/sync.go:382 +0x110f
github.com/juicedata/juicefs/pkg/sync.Sync.func1(0xc00048a120, 0xc000498120, 0x26fa460, 0xc0000a9480, 0x26fade0, 0xc000092300, 0xc000309ea0)
	/home/runner/go/pkg/mod/github.com/juicedata/juicefs@v0.11.1-0.20210317124003-5f38427ccdb9/pkg/sync/sync.go:627 +0xa3
created by github.com/juicedata/juicefs/pkg/sync.Sync
	/home/runner/go/pkg/mod/github.com/juicedata/juicefs@v0.11.1-0.20210317124003-5f38427ccdb9/pkg/sync/sync.go:625 +0x171

**Comment by daybug** [comment]
`-u` and `-f` failed in sftp too.

`2021/03/23 15:29:52.197432 juicefs[87239] <ERROR>: Failed to copy db_converter.py: sftp: "Failure" (SSH_FX_FAILURE)`

**Comment by davies** [comment]
@daybug sftp does not support copying permissions, will fix that.
