### ISSUE TITLE
"out of memory" when sync from s3 to bos

### ISSUE THREAD

**Issue by fakeYanss** [juicedata/juicesync#116]
The used percent of memory will rise continuously. 
You can start a process of juicesync, which do synchronizing objects from s3(or s3 compatible, like ceph and minio) to bos. And confirm it by print MEM output.
```
while true; do ps aux|grep "juice\|MEM"|grep -v grep; sleep 1; done
```
And after a while, the process will be killed by system.

**Comment by davies** [comment]
What's the objects looks like? small or big?

**Comment by fakeYanss** [comment]
All of those object is media file, about 100MB each one.

**Comment by fakeYanss** [comment]
I think it has nothing todo with file size.

When I run juicesync with s3 to s3, the percent of used memory is normal.

BOS support s3 compatible API. Replace domain from `bj.bcebos.com` to `s3.bj.bcebos.com`.

**Comment by fakeYanss** [comment]
Maybe the problem occurred in BOS go sdk. I can submit a internal ticket to BOS team, if you can ensure the problem.

**Comment by davies** [comment]
Sure, we will try to reproduce it and identify the problem.

**Comment by chnliyong** [comment]
> I think it has nothing todo with file size.
> 
> When I run juicesync with s3 to s3, the percent of used memory is normal.
> 
> BOS support s3 compatible API. Replace domain from `bj.bcebos.com` to `s3.bj.bcebos.com`.

@fakeYanss I couldn't reproduce this problem, I use the latest [juicedata/juicesync](https://github.com/juicedata/juicesync) code, the built version is:
```
juicesync -V
v0.7.0-6-g168ff93, commit 168ff93, built at 2021-06-15
```
I tried sync 50 100MiB local data files to bos, the throught is about 100MiB/s，and the memory usage of juicesync process is about 320MiB and doesn't increase.

**Comment by chnliyong** [comment]
I've also synced `s3://{{bos-bucket}}.s3.bj.bcebos.com/temp/` to `bos://{{bos-bucket}}.bj.bcebos.com/temp2/`, and the throughput is about 100MiB/s and the juicesync process memory is about 260MiB.

**Comment by fakeYanss** [comment]
I will try to reproduce it later.

And the version of my juicesync is v0.6.2. I found some problem with the latest version (`juicesync_0.7.0_Linux_x86_64.tar.gz`) .

**Comment by fakeYanss** [comment]
I reproduce it with this command:
```
nohup ./juicesync -v --threads=20 s3://ak:sk@bkt.hz-hbxycm01.becbos.baidu.com/ bos://ak:sk@bkt.bj.bcebos.com/sync_test/ >juice.log 2>&1 &
```
This is my verbose log print: [log download](https://yetanotherbucket.bj.bcebos.com/juice.log?authorization=bce-auth-v1/d592b147e31c4d85a12a335a7ad751f2/2021-07-23T07%3A49%3A52Z/2592000/host/f33c32727301320b5cca78adfca8c40b9ebc1e7a9ee0b84282c1cb0ab9dd568b)
The link is temporary and will expired in 12 hours. @davies @chnliyong

**Comment by davies** [comment]
@fakeYanss juicesync v0.6.2 use a very old version of baidubce (2018.04.01), please use 0.7 or build with latest master branch.  What's the problem you face with v0.7?

**Comment by davies** [comment]
Based on the logging, there is a leak of goroutines (should be leak from bce-sdk-go):

```
goroutine 26974 [select]:
net/http.(*persistConn).writeLoop(0xc98178cea0)
        /opt/hostedtoolcache/go/1.13.15/x64/src/net/http/transport.go:2210 +0x123
created by net/http.(*Transport).dialConn
        /opt/hostedtoolcache/go/1.13.15/x64/src/net/http/transport.go:1581 +0xb32
```

**Comment by fakeYanss** [comment]
Sorry, I cannot reproduce the memory leak with juicesync v0.7.0. Maybe I have downloaded some wrong package with proxy tool in the repository release page.
Fortunately, it works good now. And Thank you again for your help.
