### ISSUE TITLE
关于文件同步流程的优化

### ISSUE THREAD

**Issue by pxdy** [juicedata/juicesync#117]
对象存储的文件同步能否不经过本地中转，实现对象存储之间的直接同步操作？

**Comment by davies** [comment]
你是说同一个地域的对象存储，利用 COPY API 来实现服务器端的数据拷贝？确实可以加上这个优化。

**Comment by pxdy** [comment]
> 你是说同一个地域的对象存储，利用 COPY API 来实现服务器端的数据拷贝？确实可以加上这个优化。

对的。
还有一个场景，不清楚请求是否可以优化：
比如源对象文件是 50G，但是本地硬盘只要 20G，是不是能用流式方式来传输。

**Comment by davies** [comment]
@pxdy 你有碰到这个问题吗？如果 目标对象存储是支持分段上传的的话，juicesync 是不依赖本地硬盘的，直接流式传输。

**Comment by pxdy** [comment]
> @pxdy 你有碰到这个问题吗？如果 目标对象存储是支持分段上传的的话，juicesync 是不依赖本地硬盘的，直接流式传输。

如果是这样，那可是太棒了！
