### ISSUE TITLE
juicefs sync break

### ISSUE THREAD

**Issue by oneinstack** [juicedata/juicesync#128]
juicefs sync break, warn:
Jul 10 10:54:11 : 2022/07/10 10:54:11.892560 juicefs[16125] <WARNING>: Update mtime of U1126/4201/xxx.shx: chtimes /nas/U1126/4201/xxx.shx: no such file or directory [sync.go:554]

**Comment by zhijian-pro** [comment]
Please provide more information, such as commands and versions.

**Comment by davies** [comment]
It's a an expected warning.
