### ISSUE TITLE
server-side-copy when src and destination support it

### ISSUE THREAD

**Issue by Slach** [juicedata/juicesync#144]
could we implements feature
which will use s3:CopyObject API https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/gov2/s3/actions/bucket_basics.go#L202 when we try to sync s3:// -> s3:// ?

for gcs:// -> gcs:// https://cloud.google.com/storage/docs/samples/storage-copy-file

etc.

**Comment by davies** [comment]
The server-side-copy is only useful when copy objects with same vendor, region and account. Also the S3 server may still need to copy the data which means the COPY request will not be much faster than GET and PUT, we only save the  bandwidth.

So the benefits may not worth the effort, we don't have a plan for it.
