### ISSUE TITLE
Add flag to gate copy links

### ISSUE THREAD

**Issue by yujunz** [juicedata/juicesync#38]
Similar to rsync
```
        -L, --copy-links            transform symlink into referent file/dir
```

**Comment by davies** [comment]
Object storage does not support symlink, so it should always follow and copy symlink?

**Comment by yujunz** [comment]
One use case I can think of is backing up a file system to object storage and restore from it later.

We may simply transfer the symlink source as the object content if user wants to avoid duplication. At least it can preserve the original information and user may restore the symlinks manually after sync.

**Comment by davies** [comment]
Then how do we know which object is a symlink?

**Comment by yujunz** [comment]
No way for sure. But probably guess from the content, that's why I said it should be manual.

Maybe we suspend this flag for now until someone came with a reasonable use case.
