### ISSUE TITLE
update 文件 -u 比对逻辑无精确到毫秒问题

### ISSUE THREAD

**Issue by SecretSun** [juicedata/juicesync#48]
mtime := int(o.LastModified.Unix())
objs = append(objs, &Object{*o.Key, *o.Size, mtime, mtime})

是否可以支持 毫秒

**Comment by davies** [comment]
看了下 S3 的 API，LastModified 只有 秒精度，哪个对象存储的修改时间有毫秒精度？

**Comment by davies** [comment]
因为对象存储本身并不提供毫秒级精度，并且 Juicesync 也没办法在毫秒级发现数据，实现 毫秒级比对没有实际效果，暂不实现。

多谢反馈！
