### ISSUE TITLE
能支持传输时过滤某些文件吗？

### ISSUE THREAD

**Issue by zhangkuantian** [juicedata/juicesync#49]
我们有些需求是只同步目录中的部分文件，有些文件时不需要传输的，但是目前没找到有支持这个功能的参数，我们都是先把文件移到其他地方，删掉不需要传输的文件之后再同步，这样做有些繁琐，请问后续有支持文件传输过滤这个功能的开发吗？

**Comment by davies** [comment]
请问 这些需要排除的文件有什么特点？ 某个子目录，还是某种扩展名？或者用正则表达式来匹配？

**Comment by zhangkuantian** [comment]
我们现在是排除特定的文件名、文件目录，后续过滤某种扩展名以及正则表达式来匹配 都会用到

**Comment by davies** [comment]
@zhangkuantian 已经添加了  --exclude 参数，可以提供多个 正则表达式（egrep 兼容）来排除某些对象，也可以用多个 --include 来指定需要 同步的对象。 最终是被 同步的是这两个的交集。
