### ISSUE TITLE
更好地处理部分传输失败的情况

### ISSUE THREAD

**Issue by yujunz** [juicedata/juicesync#51]
可选的设计：

* 添加一下参数控制，允许这种传输失败时，抛出异常
* 将所有失败的传输项加入一个 retry list，允许用户手工重试

**Comment by davies** [comment]
现在已经默认改成当有失败的传输时， 以非0 退出，是否足够了？

目前对于所有失败的传输，都会有对应的 ERROR ，已经可以看到 并选择重试。
