### ISSUE TITLE
3P 数据跨云传多久？

### ISSUE THREAD

**Issue by JoeShi** [juicedata/juicesync#74]
Q1. 3P 数据跨云传多久？

Q2. 拷贝的时候会拷贝metadata 么？

Q3. 支持集群拷贝么？

Q4. 有流量统计或者进度统计么？

**Comment by davies** [comment]
Q1: 主要取决于可用的带宽，如果用 10Gb 带宽，24 小时能够拷贝 100T，10 天就够了。

Q2: 这是哪种 metadata？目前可能不支持，可以考虑增加这个功能。

Q3: 目前不支持，只能手动按目录做下拆分，不同节点同步不同目录的数据。

Q4: 有的。

**Comment by JoeShi** [comment]
Q1. 单机器 10Gb 还是有些困难的吧，毕竟还要跨地域。有benchmark 指标么？

**Comment by davies** [comment]
之前内网拷贝时能够跑满 10Gb。juicesync 是多线程的，公网慢时可以多开一些线程尽量把带宽跑满，然后再多开几个节点并行做。

**Comment by JoeShi** [comment]
好的，谢谢。

**Comment by davies** [comment]
@JoeShi 正在加上 多机分布式支持： https://github.com/juicedata/juicesync/pull/75
