### ISSUE TITLE
Kerberized HDFS Support

### ISSUE THREAD

**Issue by HooinKyoma** [juicedata/juicesync#81]
Hi,juicesync is an awsome data sync tool.But I found that when I start to sync data from 2 hdfss,it shows "no available namenodes: write tcp x.x.x.x:59738->x.x.x.x:8020: write: broken pipe".Does it support kerberized HDFS?Thank you.

**Comment by davies** [comment]
@HooinKyoma Well received, the library [1] used here does support kerberized HDFS, will support it soon. 

[1] github.com/colinmarc/hdfs

**Comment by davies** [comment]
@HooinKyoma Kerberized HDFS is supported now, please build from master branch, or wait for a new release.

**Comment by davies** [comment]
@HooinKyoma wait, it has difficulty to talk to data node, we are working on it.

**Comment by HooinKyoma** [comment]
Got it.Thank you for your hard work!

**Comment by davies** [comment]
Created https://github.com/colinmarc/hdfs/issues/258

**Comment by davies** [comment]
juicesync had upgrade HDFS client to 2.2.0 to address this issue, so Kerberized HDFS is fully supported. cc @HooinKyoma

**Comment by davies** [comment]
@HooinKyoma Please try juicesync v0.6.1
