### ISSUE TITLE
希望支持天翼云 对象存储【OOS】

### ISSUE THREAD

**Issue by bitboxclub** [juicedata/juicesync#84]
希望和天翼元对象存储进行对接。
天翼云对象存储的开发者文档可以通过这里获取。
https://www.ctyun.cn/help2/10000101/10001738
有2个文档
对象存储网络 和 其他区域他们所对应的endpoint
可以在这里查到
https://www.ctyun.cn/help2/10000101/10474062

**Comment by asalis** [comment]
aliyun oss 和本地ubuntu同步命令要怎么写

**Comment by davies** [comment]
@asalis  拷贝数据到 OSS 的话： ./juicefs /loca/path/  oss://$AK:$SK@bucket/prefix/
