### ISSUE TITLE
请增加对天翼云（融合版）的支持

### ISSUE THREAD

**Issue by daybug** [juicedata/juicesync#91]
感谢作者的这个产品，实测速度非常快，尤其注意到最近增加了对天翼云对象存储的支持。不过天翼云对象存储有两个版本（经典版、融合版），其中融合版基于ceph实现，测试过程中发现使用oos://前缀无法访问融合版（我测试使用的endpoint为http://cqoss.xstore.ctyun.cn）。

**Comment by davies** [comment]
如果这个 API 是 S3兼容，可以试一下把它当成 S3来访问？  s3://cqoss.xstore.cyyun.cn/

**Comment by daybug** [comment]
SDK是兼容S3的，试过S3依然不行，不过我试了下obs倒是可以。

**Comment by davies** [comment]
可能是 默认 的 region 写法不同，你们提个 PR 吧

**Comment by davies** [comment]
Fixed by #92 , Thanks
